version: '3.8'
services:
  app:
    build: .
    image: thymeleaf-img:latest
    container_name: thymeleaf-cont
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/thymeleaf
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=-098
    ports:
      - "1984:1984"
    volumes:
      - ./src/main/resources/photo-uploads:/photo-uploads
    restart: always
    networks:
      - global-network


networks:
  global-network:
    external: true
