version: '3.8'
services:
  app:
    build: .
    image: thymeleaf-img:latest
    container_name: thymeleaf-cont
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/thymeleaf
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=-098
    ports:
      - "1984:1984"
    volumes:
      - ./src/main/resources/photo-uploads:/photo-uploads
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: thymeleaf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: -098
    ports:
      - ":5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#    knk
#  PostgreSQL Database directory appears to contain a database; Skipping initialization
#
#2024-11-06 05:47:37.463 UTC [1] FATAL:  database files are incompatible with server
#2024-11-06 05:47:37.463 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 14.13 (Debian 14.13-1.pgdg120+1).
